name: mini_getx
description: The fork getx, this is a mini version getx, Only retain state management, remove route、connect、bing...
version: 5.0.6
homepage: https://github.com/jonataslaw/getx
repository: https://github.com/luoyi58624/getx.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web: any

dev_dependencies:
  flutter_lints: ^4.0.0
